---
- hosts: web
  become: true
  become_user: root
  vars:
    src_path: /root/Ansible-Play
    dest_path: /var/www/html

  tasks:
  - name: Install Apache/ Httpd
    yum:
      name: httpd
      state: latest

    notify: enable httpd

  - name: Copy Index file
    copy:
      src={{src_path}}/index.html
      dest={{dest_path}}

    notify: Restart Httpd

  handlers:
  - name: Restart Httpd
    service:
      name: httpd
      state: restarted

  - name: enable httpd
    service:
      name: httpd
      enabled: yes
