---
- hosts: web
  become: true
  become_user: root

  tasks:
  - name: Install List of packages
    yum:
      name: '{{item}}'
      state: latest

    loop:
      - wget
      - tree
      - unzip
      - vim
